name: churn-prediction-env 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    # Ambil daftar dari requirements.txt
    - pandas==2.2.3
    - numpy==2.2.6
    - scikit-learn==1.6.1
    - mlflow==2.22.0
    - dagshub==0.5.10
    - matplotlib==3.10.3
    - seaborn==0.13.2